title: Swarnabh Kashyap # your name (or website title) here
logo: "/images/sk.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring Data Analyst. Current Graduate student in Data Science at Rochester Institute of Technology.
  <br><br>
  Looking for Internship opportunities!
  <br><br>
  <a href="https://www.linkedin.com/in/swarnabh-kashyap-a83645147/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
